--Recommended Analysis:
--Sum of quantity sold
--Sum of revenue
--Average revenue
--Quantity of items sold
--Quantity of items sold by each sales_person and in each region.
--Revenue generated by item according to regions
--Revenue by Sales_person
--Sales and Revenue by Month and Year
--Count of Orders by unique customers



--Preview my dataset
SELECT *
FROM "Sales"

--Count of my dataset
SELECT COUNT (*)
FROM "Sales"

--Key metrics
--Sum of revenue
--Sum of quantity sold
--Average revenue

SELECT 
    SUM(Revenue) AS total_revenue,
    SUM(quantity) AS total_quantity,
    ROUND(AVG(Revenue), 2) AS average_revenue
FROM "Sales"

--Count of customers
SELECT COUNT(DISTINCT
	customer_id)
FROM "Sales"

--Quantity of items sold by each sales_person and in each region.
SELECT
  sales_person,
  item,
  region,
  COUNT(DISTINCT item) AS distinct_item_count,
  SUM(Quantity) AS total_quantity_sold
FROM "Sales"
GROUP BY item,sales_person,region
ORDER BY region,sales_person DESC

--Revenue generated by item according to regions
SELECT
	item,
    COUNT(DISTINCT region) AS distinct_regions,
    SUM(revenue) AS total_revenue
FROM
    "Sales"
GROUP BY
    item
ORDER BY
    total_revenue DESC
	
--Revenue by Sales_person
SELECT
    sales_person,
    SUM(revenue) AS total_revenue_generated
FROM
    "Sales"
GROUP BY
    sales_person
ORDER BY
    total_revenue_generated DESC
	
--Sales and Revenue by Month and Year
SELECT
    EXTRACT(YEAR FROM date) AS sales_year,
    EXTRACT(MONTH FROM date) AS sales_month,
    item,
    SUM(quantity) AS total_quantity_sold,
    SUM(revenue) AS total_revenue
FROM "Sales"
GROUP BY EXTRACT(YEAR FROM date), EXTRACT(MONTH FROM date), item
ORDER BY sales_year DESC, sales_month DESC, total_revenue DESC;

-- Count of Orders by unique customers
SELECT COUNT(DISTINCT customer_id) AS customer_count,
			 item,
			SUM(quantity) As total_products_ordered
FROM "Sales"
GROUP BY item;


			 




